spring:
  application:
    name: productservice
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        physical_naming_strategy: com.zhaops.productservice.product.util.HibernatePhysicalNamingNamingStrategy
    database: H2
    
  zipkin:
    base-url: http://172.16.100.177:9411
    enabled: true
    
  sleuth:
    sampler:
      percentage: 1.0
      
  redis:
    host: 172.16.100.177
    port: 6379
    password:
    database: 0
    timeout: 5000
  
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./dbh2/dbc2m;AUTO_SERVER=TRUE
    username: sa
    password:
    schema: classpath:schema.sql
    data: classpath:data.sql
    platform: h2


  h2:
    console:
      enabled: true
      path: /h2


feign:
  hystrix:
    enabled: true

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
      
name: "zhaops1"
pass: "{cipher}41365d10cf71343ab11bf1d7a8699529509e89c840f138d8aa2a742f0008eacd"
